import Header from "@/components/Header"
import "../globals.css"
import { ClerkProvider } from '@clerk/nextjs'
import { SanityLive } from "@/sanity/lib/live"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body>
          <main>
            <Header/>
            {children}
          </main>
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  )
}
